spring.application.name=btms

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/BTMS
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Config
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000